### ISSUE TITLE
Interview feds to test clarity of homepage

### ISSUE THREAD

**Issue by kategarklavs** [18F/myusa#486]
After meeting with @esgoodman on Friday (1/2), I've decided that hallway testing (instead of sending a survey via SurveyMonkey) will be a better route to take.

I've got a preliminary list of questions ready (happy to share at today's meeting), and will touch base with Liz today about scheduling said tests.

New to-do list includes the following:

- [x] Revise questions/script
- [x] Share interview questions/script with team for feedback
- [x] Schedule hallway tests at 50UNP
- [ ] Publicize hallway tests at 50UNP (fliers)
- [ ] Conduct tests
- [ ] Prepare summary of results + distribute to team

Updated to-do list (1/26)

- [x] Revise questions/script
- [x] Share interview questions/script with team for feedback 
- [x] Email Jen Kerber to get intros to govies who might be interested in being interviewed
- [ ] Conduct tests with SF team members
- [ ] Conduct tests with other interested parties
- [ ] Prepare summary of results + distribute to team

**Comment by kategarklavs** [comment]
After meeting with @esgoodman on Friday (1/2), I've decided that hallway testing (instead of sending a survey via SurveyMonkey) will be a better route to take.

I've got a preliminary list of questions ready (happy to share at today's meeting), and will touch base with Liz today about scheduling said tests.

New to-do list includes the following:

- [ ] Revise questions/script
- [ ] Share questions/script with team for feedback
- [ ] Schedule/publicize hallway tests at 50UNP
- [ ] Conduct tests
- [ ] Prepare summary of results + distribute to team

**Comment by polastre** [comment]
:+1: @esgoodman -- I'd use interview not survey.

**Comment by kategarklavs** [comment]
Thanks for the feedback – title updated!

**Comment by kategarklavs** [comment]
Informal hallway testing, round 1, is scheduled for Monday, 1/12 from 9:30 - 11:00 AM. 

I'll camp out in the cafe with printed copies of the updated front page (along with edible incentives, aka cookies or apples). 

At this point, I'm not defining a target number of interviews for this session – I'm not sure how responsive folks will be. (If folks are eager to participate during this timeframe, I'll schedule another morning session; if the response is so-so, I'll plan an afternoon session for later in the week.)

**Comment by polastre** [comment]
Minor point -- you may want to point out on your materials how much time it is expected this will take someone.  If you told me you only needed 1-2 minutes of my time, I'm much more likely to agree than for a 10-15 minute session.

**Comment by kategarklavs** [comment]
@polastre Great point – my template specifies an average timeframe of between 5 and 10 minutes.

I expect that many interviews will take only two or three minutes, but I'd rather overestimate the required time than keep people for longer than initially stated.

**Comment by esgoodman** [comment]
From the number of questions, I'd assume a ten-minute timeframe.

**Comment by kategarklavs** [comment]
@esgoodman – Would you recommend cutting a few questions for the sake of shorter interviews? I don't want the predicted interview length to deter potential participants.

**Comment by kategarklavs** [comment]
Long story short: Interview materials are ready to go. We're waiting for final approval from union folks before I start to conduct interviews at 50UNP.

**Comment by esgoodman** [comment]
UPDATE: Now starting to do this remotely because we are still waiting for approval on hallway usability work.

**Comment by esgoodman** [comment]
# Quick summary
Raw notes as [comments on InVision project](https://projects.invisionapp.com/d/main#/console/2318574/62062701/comments)

## Split into audiences makes sense
"The way that’s broken down into the audience for agencies and developers [makes sense]. I think that those two audience groups are going to be doing very different tasks." - Joanne

## Central image/text is visually appealing but not informative
"It’s a big banner, it’s a pretty picture. But now I have to hunt to find something that’s my task. Because my task — is my task to Connect to MyUSA, right? Is there a task?" - Joanne

## Next section seems like a footer
![screen shot 2015-02-23 at 3 48 00 pm](https://cloud.githubusercontent.com/assets/10067318/6340392/a6d4af4c-bb73-11e4-8c61-0c2acd5d0fd2.png)
"I almost feel like this should be footer information because it doesn't offer more information. Are there more partners? Is it just these three? I don't really know." - Sarah

## Offerings to agencies are unclear
![screen shot 2015-02-23 at 4 06 05 pm](https://cloud.githubusercontent.com/assets/10067318/6340625/fd77e222-bb75-11e4-8043-e63a9a1b6eda.png)

### Simple and Private for whom?
"Is it really for the agencies or is it simple and private for the user? I would think that would be more for the public. Trying to reconcile MyUSA for agencies with Simple and Private. That icon — I didn’t understand how that worked. I would probably put Ease of Access." - Jonathan

### What are those tools? 
![screen shot 2015-02-23 at 3 57 18 pm](https://cloud.githubusercontent.com/assets/10067318/6340508/be611640-bb74-11e4-8f84-f7624dc0f707.png)
"It kinda sounds like they have an online tool or service to facilitate that process of getting assistance from GSA to build other services within our own agency" - Sarah 
"It's for APIs, right?" - M.

## Developers want more information 

![screen shot 2015-02-23 at 4 02 28 pm](https://cloud.githubusercontent.com/assets/10067318/6340583/68df8214-bb75-11e4-8005-888b67cc7f85.png)

"I don't like the fact that I have to sign up for something. Why can't I just explore? It's like I have to make a commitment. Why can't I just browse for more information." - M

### Words that seem to be misleading throughout the page
* Connect
* Services
* Publish
* Access

# What we did
30-minute remote interviews with 6 federal employees

# What we tested
<img src="https://github.com/18F/myusa-ux/blob/master/images/front%20page.png" height="600" />

**Comment by esgoodman** [comment]
Stable spot for interview notes [here](https://github.com/18F/myusa-ux/blob/master/research/front%20page%2020150222.md)

**Comment by jackiekazil** [comment]
:+1:
