### ISSUE TITLE
Do users trust that MyUSA provides secure access to government websites?

### ISSUE THREAD

**Issue by esgoodman** [18F/myusa#498]
MyUSA should not only provide secure access, but also effectively communicate to users *how* it is secure. 

Our hypothesis is that users do trust that MyUSA is secure.

Questions to answer include:
- [ ] How do potential users react to passwordless authentication?
- [ ] How do potential users react to signing in with outside credential providers (e.g. Google)?

**Comment by esgoodman** [comment]
I think we should just delete this issue and make two new ones -- one asking how people feel about passwordless authentication, and one asking how people feel about third-party credentials.

**Comment by polastre** [comment]
@esgoodman I'm not in favor of closing this issue.  You already have #53 for testing passwordless authentication, which I mentioned in https://github.com/18F/myusa/issues/498#issuecomment-68068085.  How users react to External Identity Providers (EIPs) is the subject of #52.

This issue is about trust, of which #52 and #53 may be sub questions to answer.  But the larger questions are still very much valid -- do users trust that MyUSA is (1) a secure government website and (2) a trustworthy place to use login credentials

**Comment by esgoodman** [comment]
Answered specifically for federal employees in [research summary doc from walkthrough with federal employees](https://github.com/18F/myusa-ux/blob/master/research/concept-evaluation-201501.md#do-users-trust-that-myusa-provides-secure-access-to-government-websites-498)

**Comment by jackiekazil** [comment]
:+1:
