### ISSUE TITLE
Authentication link is plain HTTP

### ISSUE THREAD

**Issue by konklone** [18F/myusa#649]
The login link I just clicked goes through a Mandrill link redirector:

```
http://mandrillapp.com/track/click/30288227/alpha.my.usa.gov?p=XXX
```

This makes me vulnerable to tracking and redirection attacks on a hostile network. As a well known service powering many other services, mandrillapp.com would be a high-value target for such an attack.

The mandrillapp.com link appears to work fine over HTTPS.

**Comment by NoahKunin** [comment]
Just tested again and confirmed this is still a problem. Hostile networks are real, this is a *must fix*.

**Comment by yozlet** [comment]
Fixed by turning off link tracking in the Mandrill settings (and also open tracking). Now, the link included in the email is an unmodified link to our site rather than going through Mandrill.

@NoahKunin: These tweaks were made to the Default Settings for our Mandrill account. I believe I can do a more specific tweak for MyUSA only, but I'm guessing that the preferred solution is to turn off all potential for information leakage to Mandrill - am I right?

**Comment by NoahKunin** [comment]
So very right! Re-testing now.

**Comment by yozlet** [comment]
Note that you'll still see an HTTP link (but going straight to MyUSA, not Mandrill) in mails from staging until #674 merges.

**Comment by jackiekazil** [comment]
@yozlet @NoahKunin can we close this?

**Comment by konklone** [comment]
This is resolved on staging in my testing.

**Comment by jackiekazil** [comment]
YAY! I am closing!
