### ISSUE TITLE
Fix API for benefits.gov

### ISSUE THREAD

**Issue by adelevie** [18F/myusa#678]
According to Mike from benefits.gov (Balasanyan.Mikhail@dol.gov), the Tasks API isn't saving the `url` attribute (on the `Task` model), and not saving `external_id` on the `TaskItem` model.

cc @harrisj

**Comment by harrisj** [comment]
See the https://github.com/18F/myusa/pull/685 pull request

**Comment by harrisj** [comment]
Currently this is passing its tests but it does not actually work when I attempt to do it manually. The nested attributes for `task_items` do not seem to be loaded. I actually would propose that we modify the API slightly to make modifying task_items use it own RESTful routes scoped to the task the items belong to. So, instead of doing a PUT or a POST with the task_attributes, you would do this:

* POST task/1/task_items  <--- create a task item
* PUT/DELETE task/1/task_items/2  <--- update a specific task item
* GET task/1/task_items  <--- would return all the task_items (but will also include within `task/1` response)

I think this is easier to implement within Rails and it eliminates some of the ambiguity from nested attributes. For instance, if I had a task in the DB with one item in it already and I did a PUT with a different item in the `task_items_attributes` field, does that mean I should replace the existing item with the new one or insert the new one alongside it?

What do you think? This would mean coordinating with potential users of the Tasks API, but I think it's ultimately cleaner and better for the API. Thoughts?

cc @yozlet, @jackiekazil and @juliaelman

**Comment by yozlet** [comment]
It's disturbing that tests pass despite it not actually working. Any ideas why?

**Comment by yozlet** [comment]
I think the API improvement's a good idea. Bear in mind it's a separate issue to this one, and we may want to save it for when we have actual UI for Tasks, but otherwise :+1:

**Comment by harrisj** [comment]
@yoz, no idea yet why the tests work but my manual tests fail, but it's possible that it's an issue with how the tests are written. I wonder if they are also bypassing some security mechanism that is being triggered for the nested attributes in my tests.

**Comment by harrisj** [comment]
I figured out the issue! The tests were posting JSON that looked like this

```json
{"tasks": {"name": "New Task", 
           "url": "http://wwww.gsa.gov/", 
           "task_items_attributes": [{"name": "Item 1", "external_id": "abc", "url": "http://gsa.gov/"}]}}
```
which Rails translated into parameters to the controller method like so
```ruby
{"task"=>{"name"=>"New Task",
          "task_items_attributes"=>[{"external_id"=>"abc", "name"=>Item 1", "url"=>"http://gsa.gov"}]}}
```
This does what we would expect, creating both the task record and its associated subtasks. But, in my manual tests, I was actually posting this JSON to the controller method (following an issue flagged by a MyUSA alpha user):
```json
{"name": "New Task", 
 "url": "http://wwww.gsa.gov/", 
 "task_items_attributes": [{"name": "Item 1", "external_id": "abc", "url": "http://www.gsa.gov/"}]}
```
Note the lack of a top-level `tasks` key. Rails then translates this into parameters to this hash
```ruby
{"name"=>"New Task", 
 "task_items_attributes"=>[{"external_id"=>"abc", "name"=>"Item 1", "url"=>"http://www.gsa.gov"}],
 "task"=>{"name"=>"New Task"l}}
```

Why? I don't know, but I think it's a result of trying to be clever and supporting both JSON and regular form-encoded parameters as input. Notice though that there is a `tasks` top-level key in this parameters hash, but it doesn't include `task_items_attributes`. So, it creates the task, but not the task items, because that key is a top-level attribute and not within the hash under the `tasks` tree. And this doesn't return an error because there is still a top-level `tasks` key. Argh.

To remedy this, I am looking to see if I can force it to accept only JSON input and then I can throw an exception if there is no top-level `tasks` key. I do not want to throw an exception if it can't find a `task_items_attributes` key since users should be allowed to create tasks without items.

**Comment by jackiekazil** [comment]
YAY!

On Thu, Jul 2, 2015 at 9:44 AM, Jacob Harris <notifications@github.com>
wrote:

> I figured out the issue! The tests were posting JSON that looked like this
>
> {"tasks": {"name": "New Task",
>            "url": "http://wwww.gsa.gov/",
>            "task_items_attributes": [{"name": "Item 1", "external_id": "abc", "url": "http://gsa.gov/"}]}}
>
> which Rails translated into parameters to the controller method like so
>
> {"task"=>{"name"=>"New Task",
>           "task_items_attributes"=>[{"external_id"=>"abc", "name"=>Item 1", "url"=>"http://gsa.gov"}]}}
>
> This does what we would expect, creating both the task record and its
> associated subtasks. But, in my manual tests, I was actually posting this
> JSON to the controller method (following an issue flagged by a MyUSA alpha
> user):
>
> {"name": "New Task",
>  "url": "http://wwww.gsa.gov/",
>  "task_items_attributes": [{"name": "Item 1", "external_id": "abc", "url": "http://www.gsa.gov/"}]}
>
> Note the lack of a top-level tasks key. Rails then translates this into
> parameters to this hash
>
> {"name"=>"New Task",
>  "task_items_attributes"=>[{"external_id"=>"abc", "name"=>"Item 1", "url"=>"http://www.gsa.gov"}],
>  "task"=>{"name"=>"New Task"l}}
>
> Why? I don't know, but I think it's a result of trying to be clever and
> supporting both JSON and regular form-encoded parameters as input. Notice
> though that there is a tasks top-level key in this parameters hash, but
> it doesn't include task_items_attributes. So, it creates the task, but
> not the task items, because that key is a top-level attribute and not
> within the hash under the tasks tree. And this doesn't return an error
> because there is still a top-level tasks key. Argh.
>
> To remedy this, I am looking to see if I can force it to accept only JSON
> input and then I can throw an exception if there is no top-level tasks
> key. I do not want to throw an exception if it can't find a
> task_items_attributes key since users should be allowed to create tasks
> without items.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/myusa/issues/678#issuecomment-118037949>.
>



-- 
Jacqueline Kazil | @jackiekazil

**Comment by harrisj** [comment]
Okay, I found why Rails is doing this. It's part of the normal behavior of [wrap_parameters](http://guides.rubyonrails.org/action_controller_overview.html#json-parameters) which we had enabled in an initializer:

> Also, if you've turned on config.wrap_parameters in your initializer or calling wrap_parameters in your controller, you can safely omit the root element in the JSON parameter. The parameters will be cloned and wrapped in the key according to your controller's name by default. 

Following a reference to [Rails' ParamsWrapper](http://api.rubyonrails.org/classes/ActionController/ParamsWrapper.html), it looks like I can tell it explicitly which top-level params to copy into the `task` key by adding the following line to the `TasksController`:

```ruby
wrap_parameters :task, include: [:name, :url, :completed_at, :task_items_attributes]
```

This is a bit redundant to the field access settings at the bottom of the controller, and I was hoping that Rails would magically figure it out from the class and its `accepts_nested_attributes` for the TaskItems, but no dice. Still, this seemingly solves the problem, and we've all learned something new about how Rails tries to be groovy and flexible.

**Comment by harrisj** [comment]
Applied fix to Pull Request #685

**Comment by yozlet** [comment]
Wow, well done!

**Comment by jackiekazil** [comment]
:+1: :star2: :us: :star2:
