### ISSUE TITLE
Code / create draft of 'contact us' page 

### ISSUE THREAD

**Issue by jackiekazil** [18F/myusa#728]
Required for #723.

**Comment by mkhandekar** [comment]
@juliaelman, here's a mock up of the contact modal. Since we already have a few variations for the heads and footers, I wanted to simplify the choices for the contact modal. This way it doesn't matter if a visitor is logged in or not. The typography and form design is the same as the Permissions page, and the modal design is same as the help modals on the Permissions page. Let me know if you have any questions!

**Sketch file is on Drive: [15-07-28_Contact.sketch](https://drive.google.com/open?id=0B4yIa0Upv1JJejBBNGZheHRIeDQ)**

**Contact Modal**

![contactmodal](https://cloud.githubusercontent.com/assets/1598889/8936167/649ab30c-3516-11e5-893d-66e1e7826f0d.png)

**Help Modal**

![4_helpmodal](https://cloud.githubusercontent.com/assets/1598889/8936289/f9fbbffe-3516-11e5-9326-8152badb3ff4.png)

**Comment by yozlet** [comment]
Should we be asking the user to click again to close the modal after they've sent the message? I wonder if it might be better to have the modal roll up to a small confirmation message while re-enabling the rest of the page.
